timeout: 5
triggers:
  - name: merge-request
    type: github_pr
    runs:
      - name: unit-test
        container: python:3.5-alpine
        host-tag: amd64
        script: unit-test

      - name: flake8
        container: python:3.5-alpine
        host-tag: amd64
        script: flake8

  # This run is just handy for demonstration purposes as documented in the
  # tutorial
  - name: post-merge
    type: git_poller
    params:
      GIT_URL: "https://github.com/linaro-technologies/jobserv.git"
      GIT_POLL_REFS: "refs/heads/master"
    runs:
      - name: flake8
        container: python:3.5-alpine
        host-tag: amd64
        script: flake8

scripts:
  flake8: |
    #!/bin/sh -ex
    pip3 install flake8 flake8-junit-report==2.1.0
    flake8 --ignore=E722 --exclude=migrations/ ./ | tee flake8.txt
    flake8_junit flake8.txt /archive/junit.xml

  unit-test: |
    #!/bin/sh -ex
    apk --no-cache add git python3-dev musl-dev gcc openssl libffi-dev openssl-dev
    git config --global user.email "cibot@example.com"
    git config --global user.name "cibot"
    ./unit-test.sh
